name: mantidimaging-dev
channels:
  - mantid/label/main
  - dtasev
  - astra-toolbox
  - conda-forge
  - ccpi
  - algotom
  - intel
dependencies:
  - mantidimaging>=2.5.0,<2.6.0
  - pip
  - pip:
      - coveralls==3.3.*
      - yapf==0.31.*
      - mypy==0.910
      - flake8==3.9.*
      - testfixtures==6.18.*
      - gitpython==3.1.*
      - pylint==2.11.*
      - sphinx==4.2.*
      - git+https://github.com/samtygier-stfc/sphinx-multiversion.git@prebuild_command
      - isort==5.9.*
      - eyes-images==4.25.*
      - parameterized==0.8.*
      - pre-commit==2.15.*
      - flake8-bugbear==22.9.*
  - pytest==7.1.*
  - pytest-cov==3.0.*
  - pytest-randomly==3.12.*
  - pytest-xdist==2.5.*
  - coverage==6.4.*
  - pyfakefs==5.0.*
  - pyinstaller==5.7.*
