name: mantidimaging-dev
channels:
  - mantidimaging/label/unstable
  - dtasev
  - astra-toolbox
  - conda-forge
  - ccpi
  - algotom
  - intel
dependencies:
  - mantidimaging>=2.5.0
  - conda-forge::numexpr # https://github.com/mantidproject/mantidimaging/issues/1774
  - pip
  - pip:
      - sphinx==7.2.*
      - git+https://github.com/samtygier-stfc/sphinx-multiversion.git@prebuild_command
      - eyes-images==5.20.*
  - yapf==0.40.*
  - mypy==1.8
  - types-requests
  - types-PyYAML
  - types-docutils
  - pytest==7.4.*
  - pytest-cov==4.1.*
  - pytest-randomly==3.15.*
  - pytest-xdist==3.3.*
  - testfixtures==7.2.*
  - gitpython==3.1.*
  - coverage==6.5.*
  - coveralls==3.3.*
  - pyfakefs==5.3.*
  - parameterized==0.9.*
  - pyinstaller==6.1.*
  - sarepy=2020.07 # For building old docs
  - make==4.3
  - ruff=0.3.2
  - pre-commit==3.5.*

