name: mantidimaging-dev
channels:
  - mantidimaging/label/unstable
  - conda-forge
  - ccpi
  - algotom
  - https://software.repos.intel.com/python/conda/
dependencies:
  - mantidimaging>=2.5.0
  - conda-forge::numexpr # https://github.com/mantidproject/mantidimaging/issues/1774
  - pip
  - pip:
      - eyes-images==5.23.*
  - yapf==0.40.*
  - mypy==1.8
  - types-requests
  - types-PyYAML
  - types-docutils
  - pytest==7.4.*
  - pytest-cov==4.1.*
  - pytest-randomly==3.15.*
  - pytest-xdist==3.3.*
  - testfixtures==7.2.*
  - gitpython==3.1.*
  - coverage==7.3.*
  - coveralls==4.0.*
  - pyfakefs==5.3.*
  - parameterized==0.9.*
  - pyinstaller==6.9.*
  - pyright==1.1.*
  - make==4.3
  - ruff=0.3.7
  - pre-commit==3.5.*
  - sphinx==7.2.*
  - pydata-sphinx-theme==0.15.*
  - sphinx-copybutton==0.5.*
  - sphinx-design==0.6.*
  - ipp=2021.12 # https://github.com/mantidproject/mantidimaging/issues/2354
