name: Convert PR to Draft PR on Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  convert-to-draft:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Convert PR to Draft
        uses: JackEAllen/DraftOnChangeRequested@v1.0.0
        with:
          github-token: ${{ secrets.ACTION_CONVERT_TO_DRAFT }}
